version: "3.9"
services:
  liferay:
    container_name: liferay
    image: liferay/portal:7.4.3.23-ga23
    ports:
      - "80:8080"
    networks:
      bridge:
    volumes:
      - ./tomcat/web.xml:/opt/liferay/tomcat/webapps/ROOT/WEB-INF/web.xml
      - ./tomcat/portal-log4j-ext.xml:/opt/liferay/tomcat/webapps/ROOT/WEB-INF/classes/META-INF/portal-log4j-ext.xml
    environment:
      - LIFERAY_LOCALES_PERIOD_ENABLED=en_US,zh_TW
      - LIFERAY_LOCALES_PERIOD_BETA=eu_ES,bg_BG,ca_AD,hr_HR,cs_CZ,da_DK,nl_BE,en_GB,en_AU,et_EE,gl_ES,el_GR,iw_IL,hi_IN,in_ID,it_IT,kk_KZ,ko_KR,lo_LA,lt_LT,ms_MY,nb_NO,fa_IR,pl_PL,pt_PT,ro_RO,ru_RU,sr_RS,sr_RS_latin,sl_SI,sk_SK,ta_IN,tr_TR,uk_UA,vi_VN
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_LOCALE=en_US
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_TIME_PERIOD_ZONE=Asia/Shanghai
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS_PERIOD_VERIFY=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_REQUIRED=false
      - LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_REDIRECT_PERIOD_ON_PERIOD_EXPIRE=true
      - LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_AUTO_PERIOD_EXTEND=true
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_HOST_PERIOD_ENABLED=true
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_PORT_PERIOD_ENABLED=true
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_PROTOCOL_PERIOD_ENABLED=true
      - LIFERAY_MESSAGE_PERIOD_BOARDS_PERIOD_MESSAGE_PERIOD_FORMATS_PERIOD_DEFAULT=html
      - LIFERAY_INCLUDE_MINUS_AND_MINUS_OVERRIDE=portal-developer.properties
networks:
  bridge:

